# Autogenerated file
def render(type, row, col):
    yield """<!DOCTYPE html>
<html>
  <head>
    <meta charset=\"utf-8\">
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">
    <title>Pico W</title>
    <link rel=\"stylesheet\" href=\"bulma.min.css\">
  </head>
  <body>
    <div class=\"container is-fluid is-mobile is-centered\">
      <section class=\"columns \">
        <div class=\"column\"></div>

        <div class=\"column\">

          <div class=\"level\">
            <div class=\"level-item has-text-centered\">
              <figure class=\"image is-128x128\">
                <img src=\"computer.svg\" alt=\"Pico W Icon\" />
              </figure>
            </div>
          </div>

          <form class=\"box\" action=\"\" method=\"POST\">

            <div class=\"level\">
              <div class=\"level-item has-text-centered\">
                <div class=\"columns\">
                  <div class=\"field is-grouped\">
                    <div class=\"field-body\">
                      <div class=\"field\">
                        <div class=\"control\">

                          <div class=\"column\">
                            <div class=\"field is-grouped is-hortizontal\">
                              """
    if {{row}} == 0 and {{ col}} == 0:
        yield """                                """
        if {{ type }} == 'R':
            yield """                                  """
# Autogenerated file
            def render1(val):
                yield """<label class=\"radio\">
  <input type=\"radio\" name=\"square\" value=\""""
                yield str(val)
                yield """\" >
</label>
"""
            yield from render1()
            yield """                                  """
        yield """                                """
    else:
        yield """                                  """
# Autogenerated file
        def render2(type):
            yield """<div class=\"field\"><label class=\"label is-medium\"> """
            yield str(type)
            yield """ </label></div>
"""
        yield from render2(type)
        yield """                                  """
    yield """                                """
